### PR TITLE
Fix LDAP match vs multivalue attributes.

### PR DESCRIPTION
**Pull request by Mutisk-zz**
## Proposed Changes

Make match work when LDAP attribute queries return a lists of strings, as happens for multi-value attributes.

The previous code tries to do weird things by exchanging the arguments being put in to re:run(). Bidirectional match might seem to work when the regular expression is just a couple of plaintexts, but is actually really wrong and also causes confusing log messages when your RE-expression end up in the string matching. 

Secondly it seemed to handle multi-valued LDAP results by concatenating them into strings like "First_item;second_item" which makes for very interesting results when you try to match against R.Es like ^read$

This change guards against cases when the LDAP query evaluates to a list and fallbacks to regular do_match when the arguments aren't lists of strings.

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes issue #100)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask on the
mailing list. We're here to help! This is simply a reminder of what we are
going to look for before merging your code._

- [ ] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [x] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@Mutisk Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-auth-backend-ldap&pullRequestId=101)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/rabbitmq-auth-backend-ldap&pullRequestId=101) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@Mutisk Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-auth-backend-ldap&pullRequestId=101)!

**Review by michaelklishin — CHANGES_REQUESTED** [review]
LDAP query evaluation is a pretty complex area of code, so we won't accept this without tests.

Tests would also demonstrate the intent of the change and provide some material for documentation improvements/extensions.

**Comment by Mutisk-zz** [comment]
As stated in #100, I need help in writing integration tests for this. N.B. There is still a check match_bidirectionally in the test suite. My PR did not break it despite removing the code do_match_bidirectionally. (I do believe bi-direction with regular expressions is fundamentally flawed).

See #100 for configuration, reproducing and expected behaviour.

**Comment by michaelklishin** [comment]
We will add integration tests but it's unlikely that it will happen before 3.7.9 ships.

**Review by lukebakken — APPROVED** [review]

**Comment by lukebakken** [comment]
@Mutisk thank you!

**Comment by Mutisk-zz** [comment]
@lukebakken Thanks a lot, you too. I reviewed the test case and while it makes sense to me, I'm still not entirely sure how to make sure the LDAP seed is populated with valid data. Is there any documentation about how to think regarding the tests/test suite? (or maybe it's obvious & I'm just an erlang newb.)

In the end we implemented RBAC with just using groups instead, but it's nice if my efforts in debugging what went on with multiple attributes helps the project, which I believe it does. :)

**Comment by lukebakken** [comment]
> Is there any documentation about how to think regarding the tests/test suite?

No, but here was my general process since I had never written a test for this project either -

First, create a failing test ([commit](https://github.com/rabbitmq/rabbitmq-auth-backend-ldap/pull/101/commits/b31145758d154d54724bf1ef6be7b27e9db23256)). I copied the code from the current multidirectional match test and added a [new user](https://github.com/rabbitmq/rabbitmq-auth-backend-ldap/pull/101/commits/b31145758d154d54724bf1ef6be7b27e9db23256#diff-5ecb20c706d82d8579b4dc4693961df5R188) for the new test. Users are inserted into the LDAP server when the test suite is run (during the per-group init phase [here](https://github.com/rabbitmq/rabbitmq-auth-backend-ldap/blob/master/test/system_SUITE.erl#L158)). Since we don't have the `postOfficeBox` attribute available I decided to use `description`. Running the tests with that commit fails with the exact same RE matches as your original report.

I then merged those changes into your branch to confirm that your changes fixed the issue.

If you have questions about this or other Erlang projects, drop me a line. Thanks!

**Pull request merged**
