### PR TITLE
Setup slapd(8)

### PR DESCRIPTION
**Pull request by dumbbell**
Setup slapd(8) at the beginning of the testsuite instead of relying on an external script to configure it.

This way, if OpenLDAP server is installed, `make ct-system` should work. `TESTING.md` is updated with this new information.

It also means the following resources are now unused:
* The Docker and Vagrant files
* `setup.sh` and `seed.sh` in the `example` directory

### CODE REVIEW

**Review by lukebakken — APPROVED** [review]
For what it's worth, I have used the Vagrant solution to run OpenLDAP while running the LDAP test suite on Windows. The simplification here seems worth losing that ability.

**Comment by dumbbell** [comment]
Oops, I should perhaps revive that file then!

**Comment by lukebakken** [comment]
It's more than just the `Vagrantfile`. Don't worry about it. If I ever _need_ to do that again, I can go back into history.

**Comment by dumbbell** [comment]
Ok :-) Sorry, I went a bit to fast with the cleanup...

**Comment by dumbbell** [comment]
Backported to 3.7.x (#123) and 3.8.x (#122).

**Pull request merged**
